# Generated by Django 4.0.2 on 2022-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Aws', 'Aws'), ('Cyber', 'Cyber')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='dificulty',
            field=models.CharField(choices=[('HARD', 'HARD'), ('MEDIUM', 'MEDIUM'), ('SOFT', 'SOFT')], max_length=15),
        ),
    ]
